apps/accounts/urls.py
from django.urls import path, reverse_lazy
from .views import login_view, logout_view, signup_view
from django.contrib.auth import views as auth_view

app_name = 'account'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', signup_view, name='signup'),

    # password reset
    path('reset-password/',
         auth_view.PasswordResetView.as_view(success_url=reverse_lazy("account:password_reset_done"))),
    path('reset-password-done/', auth_view.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-confirm/<uidb64>/<token>/',
         auth_view.PasswordResetConfirmView.as_view(success_url=reverse_lazy("account:password_reset_complete")),
         name='password_reset_confirm'),
    path('reset-complete/', auth_view.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    # password change
    path('change-password/',
         auth_view.PasswordChangeView.as_view(template_name='registration/password_change_form.html',
                                              success_url=reverse_lazy(
                                                  "account:password_change_done")),
         name='change_password'),
    path('change-password-done/',
         auth_view.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
]

apps/blog/urls.py
from django.urls import path
from .views import blog_view, blog_single

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='blog'),
    path('<int:pk>/', blog_single, name='blog-single'),
]

apps/contact/urls.py
from django.urls import path
from .views import contact
app_name = 'contact'

urlpatterns = [
    path('', contact, name='contact')
]

apps/course/urls.py
from django.urls import path
from .views import course_view, add_course, course_detail
app_name = 'course'

urlpatterns = [
    path('', course_view, name='list'),
    path('course/<int:pk>/', course_detail, name='detail'),
    path('add-course/', add_course, name='add_course'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls.i18n import i18n_patterns

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

schema_view = get_schema_view(
    openapi.Info(
        title="University API Docs",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    # SWAGGER
    path('', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # ADMIN
    path('admin/', admin.site.urls),
    # MVT Pattern
    # path('t/', include('apps.university.urls', namespace='university')),
    # path('blog/', include('apps.blog.urls', namespace='blog')),
    # path('comment/', include('apps.comment.urls', namespace='comment')),
    # path('courses/', include('apps.course.urls', namespace='course')),
    # path('contact/', include('apps.contact.urls', namespace='contact')),
    # path('auth/', include('apps.accounts.urls', namespace='account')),
    # DRF
    path('api-auth/', include('rest_framework.urls')),
    path('api/accounts/', include('apps.accounts.api.urls')),
    path('api/blog/', include('apps.blog.api.urls')),
    path('api/comment/', include('apps.comment.api.urls')),
    path('api/contact/', include('apps.contact.api.urls')),
    path('api/course/', include('apps.course.api.urls')),
    path('api/university/', include('apps.university.api.urls')),
    # JWT
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.conf import settings

class Category(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title


class Blog(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True)
    title = models.CharField(max_length=221)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog/')
    content = RichTextField()
    tags = models.ManyToManyField(Tag)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

apps/comment/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.conf import settings


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)
    post = models.ForeignKey('blog.Blog', on_delete=models.CASCADE)
    top_level_comment_id = models.IntegerField(null=True, blank=True)
    message = models.TextField()
    is_reply = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.author.full_name:
            return f'{self.author.full_name}s comment'
        return self.author.username

    @property
    def get_children(self):
        children = Comment.objects.filter(top_level_comment_id=self.id).exclude(id=self.id)
        return children


def comment_pre_save(instance, sender, *args, **kwargs):
    if instance.parent is not None:
        instance.is_reply = True


def comment_post_save(instance, sender, created, *args, **kwargs):
    if created:
        if instance.top_level_comment_id is None:
            top_level_comment_id = instance.id
            parent = instance
            while True and parent.parent is not None:
                top_level_comment_id = parent.parent.id
                parent = parent.parent
            instance.top_level_comment_id = top_level_comment_id
            instance.save()


pre_save.connect(comment_pre_save, sender=Comment)
post_save.connect(comment_post_save, sender=Comment)

apps/contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=221)
    phone = models.CharField(max_length=221)
    email = models.EmailField(max_length=221)
    message = models.TextField()

    def __str__(self):
        return self.name

apps/course/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.conf import settings


def path_to_course_image(instance, filename):
    category = instance.category.title
    course = instance.title
    return '{0}/{1}/images/{2}'.format(category, course, filename)


def path_to_lesson_video(instance, filename):
    category = instance.course.category.title
    course = instance.course.title
    lesson = instance.title
    return '{0}/{1}/{2}/videos/{3}'.format(category, course, lesson, filename)


class Course(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True)
    title = models.CharField(max_length=221)
    image = models.ImageField(upload_to=path_to_course_image)
    category = models.ForeignKey('blog.Category', on_delete=models.SET_NULL, null=True, blank=True)
    tags = models.ManyToManyField('blog.Tag', blank=True)
    description = RichTextField()
    detail = RichTextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=221)
    duration = models.CharField(max_length=21)
    video = models.FileField(upload_to=path_to_lesson_video)
    description = RichTextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

apps/contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = filed_name.capitalize()

apps/blog/api/v1/views.py
from rest_framework.response import Response
from rest_framework import status, generics, permissions
from django.db.models import Q

from .permission import IsOwnUserOrReadOnly
from ...models import Category, Tag, Blog
from .serializers import CategorySerializer, TagSerializer, BlogSerializer


class CategoryListView(generics.ListAPIView):
    # http://127.0.0.1:8000/api/blog/v1/category-list/
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class TagListView(generics.ListAPIView):
    # http://127.0.0.1:8000/api/blog/v1/tag-list/
    queryset = Tag.objects.all()
    serializer_class = TagSerializer

class BloglistView(generics.CreateAPIView):
    # http://127.0.0.1:8000/api/blog/v1/blog-list-create/
    queryset = Blog
    serializer_class = BlogSerializer


class BlogRetriveUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    # http://127.0.0.1:8000/api/blog/v1/blog-rud/<int:pk>/'
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer
    permission_classes = [IsOwnUserOrReadOnly, permissions.IsAuthenticated]

apps/blog/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from .models import Blog
from apps.comment.models import Comment


def blog_view(request):
    posts = Blog.objects.all().order_by('-id')

    cat = request.GET.get('cat')
    tag = request.GET.get('tag')
    author = request.GET.get('author')
    date = request.GET.get('date')

    if cat:
        posts = posts.filter(category__title__exact=cat)

    if tag:
        posts = posts.filter(tags__title__exact=tag)

    if author:
        posts = posts.filter(author__username__exact=author)

    if date:
        posts = posts.filter(created_at__contains=date)

    context = {
        'posts': posts,
    }

    return render(request, 'blog.html', context)


def blog_single(request, pk=None):
    if request.method == "POST":
        if request.user.is_authenticated:
            message = request.POST.get('message')
            comment_id = request.POST.get('comment_id')
            top_level_comment_id = request.POST.get('top_level_comment_id')

            if message:
                comment = Comment(
                    author_id=request.user.profile.id,
                    post_id=pk,
                    message=message
                )
                if comment_id:
                    comment.parent_id = comment_id
                if top_level_comment_id:
                    comment.top_level_comment_id = top_level_comment_id
                comment.save()
                return redirect(f'/blog/{pk}#comment-list')
        return redirect('/login/')

    if pk is not None:
        post = Blog.objects.get(id=pk)
        comments = Comment.objects.filter(is_reply=False, post_id=pk)
        context = {
            'post': post,
            'comments': comments,
        }
        return render(request, 'blog-single.html', context)
    raise Http404

apps/contact/api/v1/views.py
from rest_framework import viewsets
from .serializers import ContactSerializer
from ...models import Contact


class ContactApiViewSet(viewsets.ModelViewSet):
    # http: // 127.0.0.1:8000/api/contacts/v1/<id>/
    queryset = Contact.objects.all()
    serializer_class = ContactSerializer
    http_method_names = ['get', 'post']

apps/contact/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm, Contact


# Create your views here.

def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('contact:contact')
    context = {
        'form': form
    }
    return render(request, 'contact.html', context)

apps/course/api/v1/views.py
from rest_framework import permissions, generics, status
from rest_framework.response import Response
from .permissions import IsOwnUserOrReadOnly, IsOwnForLessonUserOrReadOnly
from .serializers import CourseCreateSerializer, CourseGetSerializer, LessonGetSerializer, LessonPostSerializer
from ...models import Course, Lesson

class CourseListView(generics.ListAPIView):
    # http://127.0.0.1:8000/api/course/v1/list/
    queryset = Course.objects.all()
    serializer_class = CourseGetSerializer

class CourseCreateView(generics.CreateAPIView):
    # http://127.0.0.1:8000/api/course/v1/create/
    queryset = Course.objects.all()
    serializer_class = CourseCreateSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        obj = self.queryset.get(id=serializer.data.get('id'))
        headers = self.get_success_headers(serializer.data)
        sz = CourseGetSerializer(obj)
        return Response(sz.data, status=status.HTTP_201_CREATED, headers=headers)

class CourseRUDView(generics.RetrieveUpdateDestroyAPIView):
    # http://127.0.0.1:8000/api/course/v1/rud/<id>/
    queryset = Course.objects.all()
    serializer_class = None
    permission_classes = [IsOwnUserOrReadOnly, permissions.IsAuthenticated]

    def get_serializer_class(self):
        if self.request.method == 'GET':
            return CourseGetSerializer
        return CourseCreateSerializer


class LessonGetListView(generics.ListAPIView):
    # http://127.0.0.1:8000/api/course/v1/<course_id>/list/
    queryset = Lesson.objects.all()
    serializer_class = LessonGetSerializer
    lookup_url_kwarg = 'course_id'

    def get_queryset(self):
        qs = super().get_queryset()
        course_id = self.kwargs.get(self.lookup_url_kwarg)
        qs = qs.filter(course_id=course_id)
        return qs


class LessonPostListView(generics.CreateAPIView):
    # http://127.0.0.1:8000/api/course/v1/<course_id>/create/
    queryset = Lesson.objects.all()
    serializer_class = LessonPostSerializer
    permission_classes = [IsOwnForLessonUserOrReadOnly, permissions.IsAuthenticated]

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        obj = self.queryset.get(id=serializer.data.get('course'))
        headers = self.get_success_headers(serializer.data)
        sz = LessonGetSerializer(obj)
        return Response(sz.data, status=status.HTTP_201_CREATED, headers=headers)

apps/course/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import JsonResponse

from apps.course.models import Course
from apps.profiles.models import MyCourse


def course_view(request):
    courses = Course.objects.all().order_by('-id')
    recent_courses = Course.objects.all()

    cat = request.GET.get('cat')
    tag = request.GET.get('tag')
    author = request.GET.get('author')
    date = request.GET.get('date')

    if cat:
        courses = courses.filter(category__title__exact=cat)

    if tag:
        courses = courses.filter(tags__title__exact=tag)

    if author:
        courses = courses.filter(author__account__username__exact=author)

    if date:
        courses = courses.filter(created_at__contains=date)
    my_course_id_list = []
    my_course_list = MyCourse.objects.filter(profile_id=request.user.profile.id)
    for i in my_course_list:
        my_course_id_list.append(i.course.id)

    context = {
        'posts': courses,
        'my_course_id_list': my_course_id_list,
        "recent_courses": recent_courses
    }

    return render(request, 'courses.html', context)


def course_detail(request, pk):
    course = Course.objects.get(id=pk)

    context = {
        "course": course,
    }
    return render(request, 'course-single.html', context)


@login_required
def add_course(request):
    cid = request.GET.get('_cid')
    profile_id = request.user.profile.id
    my_courses = MyCourse.objects.filter(profile_id=profile_id)
    data = {}
    my_course_id_list = []
    for i in my_courses:
        my_course_id_list.append(i.course.id)

    if int(cid) in my_course_id_list:
        print('if')
        MyCourse.objects.filter(course_id=cid).delete()
        data['message'] = 'Kurslar royhatidan ochirildi'
    else:
        print('else')
        MyCourse.objects.create(course_id=cid, profile_id=profile_id)
        data['message'] = 'Kurslar royhatiga qoshildi'

    return JsonResponse(data, status=200)

templates/base.html
<!doctype html>
{% load static %}
{% load i18n_switcher %}
<html lang="en">

<head>
    <title>{% block title %}Free Education Template by Colorlib{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet">
    <link rel="stylesheet"
          href="{% static 'css/style.css' %}"/>

    <script nonce="883122b0-89d4-49f2-bc04-03b5e4274d86">(function (w, d) {
        !function (a, e, t, r) {
            a.zarazData = a.zarazData || {};
            a.zarazData.executed = [];
            a.zaraz = {deferred: [], listeners: []};
            a.zaraz.q = [];
            a.zaraz._f = function (e) {
                return function () {
                    var t = Array.prototype.slice.call(arguments);
                    a.zaraz.q.push({m: e, a: t})
                }
            };
            for (const e of ["track", "set", "ecommerce", "debug"]) a.zaraz[e] = a.zaraz._f(e);
            a.zaraz.init = () => {
                var t = e.getElementsByTagName(r)[0], z = e.createElement(r), n = e.getElementsByTagName("title")[0];
                n && (a.zarazData.t = e.getElementsByTagName("title")[0].text);
                a.zarazData.x = Math.random();
                a.zarazData.w = a.screen.width;
                a.zarazData.h = a.screen.height;
                a.zarazData.j = a.innerHeight;
                a.zarazData.e = a.innerWidth;
                a.zarazData.l = a.location.href;
                a.zarazData.r = e.referrer;
                a.zarazData.k = a.screen.colorDepth;
                a.zarazData.n = e.characterSet;
                a.zarazData.o = (new Date).getTimezoneOffset();
                a.zarazData.q = [];
                for (; a.zaraz.q.length;) {
                    const e = a.zaraz.q.shift();
                    a.zarazData.q.push(e)
                }
                z.defer = !0;
                for (const e of [localStorage, sessionStorage]) Object.keys(e || {}).filter((a => a.startsWith("_zaraz_"))).forEach((t => {
                    try {
                        a.zarazData["z_" + t.slice(7)] = JSON.parse(e.getItem(t))
                    } catch {
                        a.zarazData["z_" + t.slice(7)] = e.getItem(t)
                    }
                }));
                z.referrerPolicy = "origin";
                z.src = "https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z=" + btoa(encodeURIComponent(JSON.stringify(a.zarazData)));
                t.parentNode.insertBefore(z, t)
            };
            ["complete", "interactive"].includes(e.readyState) ? zaraz.init() : a.addEventListener("DOMContentLoaded", zaraz.init)
        }(w, d, 0, "script");
    })(window, document);</script>
</head>
<body>
<header role="banner">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand absolute" href="/">University</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05"
                    aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse navbar-light" id="navbarsExample05">
            <ul class="navbar-nav">
                                <li><a href="{{ request|switch_i18n:'en' }}">En</a> /</li>
                                <li><a href="{{ request|switch_i18n:'ru' }}">Ru</a> /</li>
                                <li><a href="{{ request|switch_i18n:'uz' }}">Uz</a></li>
                            </ul>
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="/">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="/courses/" >Courses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog/">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/about/">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/contact/">Contact</a>
                    </li>
                </ul>
                <ul class="navbar-nav absolute-right">
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'account:logout' %}">LogOut</a> / <a href="/profile/">Profile</a>
                    </li>
                    {% else %}
                     <li>
                        <a href="{% url 'account:login' %}">Login</a> / <a href="{% url 'account:signup' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>

            </div>
        </div>
    </nav>
</header>
{% block content %}

{% endblock %}

<footer class="site-footer">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
                <h3>University</h3>
                <p>Perferendis eum illum voluptatibus dolore tempora consequatur minus asperiores temporibus.</p>
            </div>
            <div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
                <h3 class="heading">Quick Link</h3>
                <div class="row">
                    <div class="col-md-6">
                        <ul class="list-unstyled">
                            <li><a href="#">Home</a></li>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Courses</a></li>
                            <li><a href="#">Pages</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="list-unstyled">
                            <li><a href="#">News</a></li>
                            <li><a href="#">Support</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Privacy</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
                <h3 class="heading">Blog</h3>
                <div class="block-21 d-flex mb-4">
                    <div class="text">
                        <h3 class="heading mb-0"><a href="#">Consectetur Adipisicing Elit</a></h3>
                        <div class="meta">
                            <div><a href="#"><span class="ion-android-calendar"></span> May 29, 2018</a></div>
                            <div><a href="#"><span class="ion-android-person"></span> Admin</a></div>
                            <div><a href="#"><span class="ion-chatbubble"></span> 19</a></div>
                        </div>
                    </div>
                </div>
                <div class="block-21 d-flex mb-4">
                    <div class="text">
                        <h3 class="heading mb-0"><a href="#">Dolore Tempora Consequatur</a></h3>
                        <div class="meta">
                            <div><a href="#"><span class="ion-android-calendar"></span> May 29, 2018</a></div>
                            <div><a href="#"><span class="ion-android-person"></span> Admin</a></div>
                            <div><a href="#"><span class="ion-chatbubble"></span> 19</a></div>
                        </div>
                    </div>
                </div>
                <div class="block-21 d-flex mb-4">
                    <div class="text">
                        <h3 class="heading mb-0"><a href="#">Perferendis eum illum</a></h3>
                        <div class="meta">
                            <div><a href="#"><span class="ion-android-calendar"></span> May 29, 2018</a></div>
                            <div><a href="#"><span class="ion-android-person"></span> Admin</a></div>
                            <div><a href="#"><span class="ion-chatbubble"></span> 19</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
                <h3 class="heading">Contact Information</h3>
                <div class="block-23">
                    <ul>
                        <li><span class="icon ion-android-pin"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                        </li>
                        <li><a href="#"><span class="icon ion-ios-telephone"></span><span
                                class="text">+2 392 3929 210</span></a></li>
                        <li><a href="#"><span class="icon ion-android-mail"></span><span class="text"><span
                                class="__cf_email__" data-cfemail="deb7b0b8b19ea7b1abacbab1b3bfb7b0f0bdb1b3">[email&#160;protected]</span></span></a>
                        </li>
                        <li><span class="icon ion-android-time"></span><span class="text">Monday &mdash; Friday 8:00am - 5:00pm</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row pt-5">
            <div class="col-md-12 text-center copyright">
                <p class="float-md-left">
                    Copyright &copy;<script data-cfasync="false"
                                            src="https://preview.colorlib.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by
                    <a href="https://colorlib.com/" target="_blank" class="text-primary">Colorlib</a>
                </p>
                <p class="float-md-right">
                    <a href="#" class="fa fa-facebook p-2"></a>
                    <a href="#" class="fa fa-twitter p-2"></a>
                    <a href="#" class="fa fa-linkedin p-2"></a>
                    <a href="#" class="fa fa-instagram p-2"></a>
                </p>
            </div>
        </div>
    </div>
</footer>


<div id="loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#f4b214"/>
    </svg>
</div>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.0.js+popper.min.js+bootstrap.min.js.pagespeed.jc.0rDo3iv199.js' %}"></script>
<script>eval(mod_pagespeed_pf7Mxj0mKh);</script>
<script>eval(mod_pagespeed_uUlNgJ6LBQ);</script>
<script>eval(mod_pagespeed_0qiiQNJwQs);</script>
<script src="{% static 'js/owl.carousel.min.js+jquery.waypoints.min.js+jquery.stellar.min.js+jquery.animateNumber.min.js+jquery.magnific-popup.min.js+main.js.pagespeed.jc.ccIMrLR2dJ.js' %}"></script>
<script>eval(mod_pagespeed_XwLTJlNGTU);</script>
<script>eval(mod_pagespeed_sZCowTUaIA);</script>
<script>eval(mod_pagespeed_3ZaEj_PSxN);</script>
<script>eval(mod_pagespeed_0d3Dwu63IC);</script>
<script>eval(mod_pagespeed_75EcKCeaHF);</script>
<script>eval(mod_pagespeed_ettdYNsW_9);</script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194"
        integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw=="
        data-cf-beacon='{"rayId":"74b207fb0a28bf6c","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2022.8.1","si":100}'
        crossorigin="anonymous"></script>


    <script>
        $('.c-btn').on('click', function (){
            let _cid = $(this).data('cid')

            $.ajax({
                url: '/courses/add-course/',
                data: {
                    _cid
                },
                success: function (res) {
                    alert(res.message)
                    location.reload()
                }
            })
        })


    </script>


</body>

<!-- Mirrored from preview.colorlib.com/theme/university/ by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 15 Sep 2022 14:25:40 GMT -->
</html>

templates/subscribe.html
<div class="py-5 block-22">
<div class="container">
<div class="row align-items-center">
<div class="col-md-6 mb-4 mb-md-0 pr-md-5">
<h2 class="heading">Create cool websites</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi accusantium optio und.</p>
</div>
<div class="col-md-6">
<form action="#" class="subscribe">
<div class="form-group">
<input type="email" class="form-control email" placeholder="Enter email">
<input type="submit" class="btn btn-primary submit" value="Subscribe">
</div>
</form>
</div>
</div>
</div>
</div>